parameters:
  name: ''
  pool: ''
  nugetVersion: 5.1.0
  sdkVersion: 3.1.201
  net5SdkVersion: 5.0.100
  artifactFileName: ''
  appInsightsInstrumentationKey: ''
  publishArtifacts: true

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - checkout: self
    submodules: true 
    clean: true

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet'
    inputs:
      versionSpec: ${{ parameters.nugetVersion }}

  
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      packageType: sdk
      version: ${{ parameters.sdkVersion }}
      includePreviewVersions: true
      
  - task: UseDotNet@2
    displayName: 'Use .NET 5 SDK'
    inputs:
      packageType: sdk
      version: ${{ parameters.net5SdkVersion }}
      includePreviewVersions: true

  - task: PowerShell@2
    inputs:
      targetType: Inline
      pwsh: true
      script: dotnet --info


  - task: PowerShell@2
    inputs: 
      filePath: build.ps1
      workingDirectory: ./
      arguments: Debug -appInsightsInstrumentationKey '${{ parameters.appInsightsInstrumentationKey }}'
      pwsh: true

    displayName: 'restore & build Debug'

  - task: PowerShell@2
    inputs: 
      filePath: build.ps1
      workingDirectory: ./
      arguments: Release -appInsightsInstrumentationKey '${{ parameters.appInsightsInstrumentationKey }}'
      pwsh: true

    displayName: 'restore & build Release'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    condition: and(succeeded(), ${{ parameters.publishArtifacts}})
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'

      archiveFile: ${{ parameters.artifactFileName }} 


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: SpecFlow.CI-BuildResult'
    condition: and(succeeded(), ${{ parameters.publishArtifacts}})
    inputs:
      PathtoPublish: ${{ parameters.artifactFileName }} 
      artifactType: container
      ArtifactName: 'SpecFlow.CI-BuildResult'

  - task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@19
    displayName: 'WhiteSource Bolt'
    inputs:
      advance: true 