parameters:
  name: ''
  pool: ''
  nugetVersion: 5.1.0
  sdkVersion: 3.0.100
  artifactFileName: ''
  appInsightsInstrumentationKey: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet'
    inputs:
      versionSpec: ${{ parameters.nugetVersion }}


  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core'
    inputs:
      version: ${{ parameters.sdkVersion }}

  - task: PowerShell@2
    inputs:
      targetType: Inline
      pwsh: true
      script: dotnet --info


  - task: PowerShell@2
    inputs: 
      filePath: build.ps1
      workingDirectory: ./
      arguments: Debug -appInsightsInstrumentationKey ${{ parameters.appInsightsInstrumentationKey }}
      pwsh: true

    displayName: 'restore & build Debug'

  - task: PowerShell@2
    inputs: 
      filePath: build.ps1
      workingDirectory: ./
      arguments: Release -appInsightsInstrumentationKey ${{ parameters.appInsightsInstrumentationKey }}
      pwsh: true

    displayName: 'restore & build Release'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'

      archiveFile: ${{ parameters.artifactFileName }} 


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: SpecFlow.CI-BuildResult'
    inputs:
      PathtoPublish: ${{ parameters.artifactFileName }} 
      artifactType: container
      ArtifactName: 'SpecFlow.CI-BuildResult'

  - task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@19
    displayName: 'WhiteSource Bolt'
    inputs:
      advance: true 