parameters:
  name: ''
  pool: ''
  nugetVersion: 4.6.2
  sdkVersion: 2.2.401
  artifactFileName: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet'
    inputs:
      versionSpec: ${{ parameters.nugetVersion }}


  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core'
    inputs:
      version: ${{ parameters.sdkVersion }}


  - task: PowerShell@2
    inputs: 
      filePath: build.ps1
      workingDirectory: ./
      arguments: Debug
      pwsh: true

    displayName: 'restore & build Debug'

  - task: PowerShell@2
    inputs: 
      filePath: build.ps1
      workingDirectory: ./
      arguments: Release
      pwsh: true

    displayName: 'restore & build Release'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'

      archiveFile: ${{ parameters.artifactFileName }} 


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: SpecFlow.CI-BuildResult'
    inputs:
      PathtoPublish: ${{ parameters.artifactFileName }} 
      artifactType: container
      ArtifactName: 'SpecFlow.CI-BuildResult'
