name: $(GitAssemblyInformationalVersion)

resources:
- repo: self
  clean: true

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

jobs:
- template: build.yml  
  parameters:
    name: SDK_3_1_102
    artifactFileName: '$(Build.ArtifactStagingDirectory)/SpecFlow-Windows.zip'
    appInsightsInstrumentationKey: $(AppInsightsInstrumentationKey)
    nugetVersion: 3.1.102
    pool:
      vmImage: 'windows-latest'

- template: build.yml  
  parameters:
    name: SDK_3_1_200
    artifactFileName: '$(Build.ArtifactStagingDirectory)/SpecFlow-Windows.zip'
    appInsightsInstrumentationKey: $(AppInsightsInstrumentationKey)
    nugetVersion: 3.1.200
    pool:
      vmImage: 'windows-latest'

- template: build.yml  
  parameters:
    name: SDK_5_0_100_preview_1
    artifactFileName: '$(Build.ArtifactStagingDirectory)/SpecFlow-Windows.zip'
    appInsightsInstrumentationKey: $(AppInsightsInstrumentationKey)
    nugetVersion: 5.0.100-preview.1
    pool:
      vmImage: 'windows-latest'     