// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TechTalk.SpecFlow.Specs.Features.Reports
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Using custom XSLT template for reports")]
    public partial class UsingCustomXSLTTemplateForReportsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CustomXsltTemplate.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Using custom XSLT template for reports", "In order to customize the look of the specflow reports\r\nAs a test manager\r\nI want" +
                    " to be able to specify a custom XSLT template for the report generation", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("there is a feature \'Feature with successful scenarios\' with 2 passing 0 failing 0" +
                    " pending and 0 ignored scenarios");
#line 8
 testRunner.And("there is a feature \'Feature with failing scenarios\' with 0 passing 1 failing 1 pe" +
                    "nding and 1 ignored scenarios");
#line 9
 testRunner.And("there are NUnit test execution results for the project");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Specfiy custom XSLT for NUnit execution report")]
        public virtual void SpecfiyCustomXSLTForNUnitExecutionReport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Specfiy custom XSLT for NUnit execution report", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 12
 testRunner.Given("there is an XSLT template containing", @"  <xsl:template match=""/"">
	features: <xsl:value-of select=""count(//nunit:test-suite[(child::nunit:results/nunit:test-case)])""/>
	all: <xsl:value-of select=""count(//nunit:test-case)""/>
	success: <xsl:value-of select=""count(//nunit:test-case[@executed = 'True' and @success='True'])""/>
	failure: <xsl:value-of select=""count(//nunit:test-case[@executed = 'True' and @success='False' and nunit:failure])""/>
	pending: <xsl:value-of select=""count(//nunit:test-case[@executed = 'True' and @success='False' and not(nunit:failure)])""/>
	ignored: <xsl:value-of select=""count(//nunit:test-case[@executed = 'False'])""/>
  </xsl:template>	", ((TechTalk.SpecFlow.Table)(null)));
#line 23
 testRunner.When("I generate SpecFlow NUnit execution report with the custom XSLT");
#line hidden
#line 24
 testRunner.Then("a report generated like", "\tfeatures: 2\r\n\tall: 5\r\n\tsuccess: 2\r\n\tfailure: 1\r\n\tpending: 1\r\n\tignored: 1", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Custom XSLT can include other custom XSLT")]
        public virtual void CustomXSLTCanIncludeOtherCustomXSLT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Custom XSLT can include other custom XSLT", ((string[])(null)));
#line 34
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 35
 testRunner.Given("there is an XSLT template \'custominclude.xslt\' containing", "  <xsl:template name=\"custom-template\">\r\n\tthis was generated by a custom template" +
                    "\r\n\tfeatures: <xsl:value-of select=\"count(//nunit:test-suite[(child::nunit:result" +
                    "s/nunit:test-case)])\"/>\r\n  </xsl:template>\t", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
#line 42
 testRunner.And("there is an XSLT template containing", "  <xsl:include href=\"custominclude.xslt\"/>\r\n  \r\n  <xsl:template match=\"/\">\r\n\t<xsl" +
                    ":call-template name=\"custom-template\" />\r\n  </xsl:template>\t", ((TechTalk.SpecFlow.Table)(null)));
#line 50
 testRunner.When("I generate SpecFlow NUnit execution report with the custom XSLT");
#line hidden
#line 51
 testRunner.Then("a report generated like", "\tthis was generated by a custom template\r\n\tfeatures: 2", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Custom XSLT can include built-in SpecFlow XSLT")]
        public virtual void CustomXSLTCanIncludeBuilt_InSpecFlowXSLT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Custom XSLT can include built-in SpecFlow XSLT", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 59
 testRunner.Given("there is an XSLT template containing", @"  <xsl:include href=""resource://TechTalk.SpecFlow.Reporting/TechTalk/SpecFlow/Reporting/Common/Common.xslt""/>
  
  <xsl:template match=""/"">
	the english tool text for 'GeneratedByPre' is
	<xsl:call-template name=""get-common-tool-text"">
         <xsl:with-param name=""text-key"" select=""'GeneratedByPre'"" />
	</xsl:call-template>
  </xsl:template>	", ((TechTalk.SpecFlow.Table)(null)));
#line 70
 testRunner.When("I generate SpecFlow NUnit execution report with the custom XSLT");
#line hidden
#line 71
 testRunner.Then("a report generated like", "\tthe english tool text for \'GeneratedByPre\' is\r\n\tGenerated by SpecFlow at ", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Custom XSLT can include built-in SpecFlow and custom XSLT")]
        public virtual void CustomXSLTCanIncludeBuilt_InSpecFlowAndCustomXSLT()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Custom XSLT can include built-in SpecFlow and custom XSLT", ((string[])(null)));
#line 77
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 78
 testRunner.Given("there is an XSLT template \'custominclude.xslt\' containing", "  <xsl:template name=\"custom-template\">\r\n\tthis was generated by a custom template" +
                    "\r\n\tfeatures: <xsl:value-of select=\"count(//nunit:test-suite[(child::nunit:result" +
                    "s/nunit:test-case)])\"/>\r\n  </xsl:template>\t", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
#line 85
 testRunner.And("there is an XSLT template containing", @"  <xsl:include href=""custominclude.xslt""/>
  <xsl:include href=""resource://TechTalk.SpecFlow.Reporting/TechTalk/SpecFlow/Reporting/Common/Common.xslt""/>
  
  <xsl:template match=""/"">
	the english tool text for 'GeneratedByPre' is
	<xsl:call-template name=""get-common-tool-text"">
         <xsl:with-param name=""text-key"" select=""'GeneratedByPre'"" />
	</xsl:call-template>
	<xsl:call-template name=""custom-template"" />
  </xsl:template>	", ((TechTalk.SpecFlow.Table)(null)));
#line 98
 testRunner.When("I generate SpecFlow NUnit execution report with the custom XSLT");
#line hidden
#line 99
 testRunner.Then("a report generated like", "\tthe english tool text for \'GeneratedByPre\' is\r\n\tGenerated by SpecFlow at \r\n\tthis" +
                    " was generated by a custom template\r\n\tfeatures: 2", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
