using System;
using System.Linq;
using Xunit;
using TechTalk.SpecFlow.Generator;
using FluentAssertions;

namespace TechTalk.SpecFlow.GeneratorTests
{
    
    public class TestHeaderWriterTests : TestGeneratorTestsBase
    {
        private TestHeaderWriter CreateTestHeaderWriter()
        {
            return new TestHeaderWriter();
        }

        [Fact]
        public void Should_return_version_from_a_cs_file_with_specific_generator_version()
        {
            var testHeaderWriter = CreateTestHeaderWriter();
            var result = testHeaderWriter.DetectGeneratedTestVersion(@"// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:1.4.0.0
//      SpecFlow Generator Version:1.3.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Bowling.Specflow
{
}
#endregion
");

            result.Should().NotBeNull();
            result.ToString().Should().Be("1.3.0.0");
        }

        [Fact]
        public void Should_return_version_from_a_vb_file_with_specific_generator_version()
        {
            var testHeaderWriter = CreateTestHeaderWriter();
            var result = testHeaderWriter.DetectGeneratedTestVersion(@"'------------------------------------------------------------------------------
' <auto-generated>
' This code was generated by SpecFlow (https://www.specflow.org/).
' SpecFlow Version:1.3.2.0
' SpecFlow Generator Version:1.4.0.0
' Runtime Version:2.0.50727.4927
'
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
");

            result.Should().NotBeNull();
            result.ToString().Should().Be("1.4.0.0");
        }

        [Fact]
        public void Should_return_version_from_a_cs_file_with_specflow_version()
        {
            var testHeaderWriter = CreateTestHeaderWriter();
            var result = testHeaderWriter.DetectGeneratedTestVersion(@"// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Bowling.Specflow
{
}
#endregion
");

            result.Should().NotBeNull();
            result.ToString().Should().Be("1.5.0.0");
        }

        [Fact]
        public void Should_return_null_from_other_files()
        {
            var testHeaderWriter = CreateTestHeaderWriter();
            var result = testHeaderWriter.DetectGeneratedTestVersion(@"not-a-generated-file");

            result.Should().Be(null);
        }
    }
}
