// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TechTalk.SpecFlow.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Execute hooks in specified order")]
    public partial class ExecuteHooksInSpecifiedOrderFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OrderedHookSupport.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Execute hooks in specified order", "As a developer\nI would like to be able to control the order of execution of hooks" +
                    " of the same type\nSo that I can set up and teardown my scenario accordingly", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst(string eventType, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
                    "first", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 7
 testRunner.Given("a scenario \'Simple Scenario\' as", "When I do something", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.And(string.Format("a hook \'FirstHook\' for \'{0}\' with order \'1000\'", eventType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("a hook \'ThirdHook\' for \'{0}\' with order \'3000\'", eventType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("a hook \'SecondHook\' for \'{0}\' with order \'2000\'", eventType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And(string.Format("a hook \'DefaultHook\' for \'{0}\'", eventType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And(string.Format("a hook \'FifthHook\' for \'{0}\' with order \'10001\'", eventType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("all steps are bound and pass", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "event"});
            table1.AddRow(new string[] {
                        "FirstHook"});
            table1.AddRow(new string[] {
                        "SecondHook"});
            table1.AddRow(new string[] {
                        "ThirdHook"});
            table1.AddRow(new string[] {
                        "DefaultHook"});
            table1.AddRow(new string[] {
                        "FifthHook"});
#line 18
 testRunner.Then("the hooks are executed in the order", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_Before()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("Before", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_BeforeScenario()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("BeforeScenario", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_BeforeTestRun()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("BeforeTestRun", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_BeforeFeature()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("BeforeFeature", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_BeforeScenarioBlock()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("BeforeScenarioBlock", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_BeforeStep()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("BeforeStep", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_After()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("After", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_AfterScenario()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("AfterScenario", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_AfterFeature()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("AfterFeature", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_AfterScenarioBlock()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("AfterScenarioBlock", ((string[])(null)));
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Should execute \'Before*\' SpecFlow events in the correct order, ie lowest numbers " +
            "first")]
        public virtual void ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst_AfterStep()
        {
            this.ShouldExecuteBeforeSpecFlowEventsInTheCorrectOrderIeLowestNumbersFirst("AfterStep", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
