// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.0.0.0
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TechTalk.SpecFlow.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Scoping step definitions")]
    [NUnit.Framework.IgnoreAttribute()]
    public partial class ScopingStepDefinitionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ScopedSteps.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Scoping step definitions", @"As a developer
I would like to be able to scope the step definitions (bindings) on method and class level
So that I can implement test logic differently depending on the usage context

Attribute usage:

[Scope(Tag = ""mytag"", Feature = ""feature title"", Scenario = ""scenario title"")] 

Future ideas:
* scope for previous steps ([StepContext(Step = ""my previous step for doing something"")])
* use regex in scopes ([StepContext(Scenario = ""(my )?scenario title"")])", ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scoping step definitions to tags")]
        public virtual void ScopingStepDefinitionsToTags()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scoping step definitions to tags", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 16
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n\r\n@mytag\r\nScenario: Simple Scenario\r\nWhen I do something" +
                    "", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 24
 testRunner.And("the following step definitions", "[When(\"I do something\"), Scope(Tag = \"mytag\")]\r\npublic void WhenIDoSomethingWithM" +
                    "yTag()\r\n{}\r\n\r\n[When(\"I do something\"), Scope(Tag = \"othertag\")]\r\npublic void Whe" +
                    "nIDoSomethingWithOtherTag()\r\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("the binding method \'WhenIDoSomethingWithMyTag\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scoping step definitions to features")]
        public virtual void ScopingStepDefinitionsToFeatures()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scoping step definitions to features", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 38
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\nScenario: Simple Scenario\r\nWhen I do something", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
 testRunner.And("the following step definitions", "[When(\"I do something\"), Scope(Feature = \"Simple Feature\")]\r\npublic void WhenIDoS" +
                    "omethingInSimpleFeature()\r\n{}\r\n\r\n[When(\"I do something\"), Scope(Feature = \"Other" +
                    " Feature\")]\r\npublic void WhenIDoSomethingInOtherFeature()\r\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.Then("the binding method \'WhenIDoSomethingInSimpleFeature\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scoping step definitions to scenarios")]
        public virtual void ScopingStepDefinitionsToScenarios()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scoping step definitions to scenarios", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 59
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n\r\nScenario: Simple Scenario\r\nWhen I do something", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 66
 testRunner.And("the following step definitions", "[When(\"I do something\"), Scope(Scenario = \"Simple Scenario\")]\r\npublic void WhenID" +
                    "oSomethingInSimpleScenario()\r\n{}\r\n\r\n[When(\"I do something\"), Scope(Scenario = \"O" +
                    "ther Scenario\")]\r\npublic void WhenIDoSomethingInOtherScenario()\r\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
 testRunner.Then("the binding method \'WhenIDoSomethingInSimpleScenario\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scopes can be conbined with AND")]
        public virtual void ScopesCanBeConbinedWithAND()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scopes can be conbined with AND", ((string[])(null)));
#line 79
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 80
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n@mytag\r\nScenario: Simple Scenario\r\nWhen I do something", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 87
 testRunner.And("the following step definition", "[When(\"I do something\"), Scope(Feature = \"Simple Feature\", Tag = \"mytag\")]\r\npubli" +
                    "c void WhenIDoSomethingInSimpleFeatureAndMyTag()\r\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
 testRunner.Then("the binding method \'WhenIDoSomethingInSimpleFeatureAndMyTag\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scopes can be conbined with OR")]
        public virtual void ScopesCanBeConbinedWithOR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scopes can be conbined with OR", ((string[])(null)));
#line 96
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 97
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n@mytag\r\nScenario: Simple Scenario\r\nWhen I do something\r\n" +
                    "\r\nScenario: Other Scenario\r\nWhen I do something", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 107
 testRunner.And("the following step definition", "[When(\"I do something\"), Scope(Scenario = \"Other Scenario\"), Scope(Tag = \"mytag\")" +
                    "]\r\npublic void WhenIDoSomethingInOtherScenarioOrMyTag()\r\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
 testRunner.Then("the binding method \'WhenIDoSomethingInOtherScenarioOrMyTag\' is executed twice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scoped matches have higher precedency")]
        public virtual void ScopedMatchesHaveHigherPrecedency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scoped matches have higher precedency", ((string[])(null)));
#line 116
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 118
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n\r\n@mytag\r\nScenario: Simple Scenario\r\nWhen I do something" +
                    "", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 126
 testRunner.And("the following step definitions", "[When(\"I do something\"), Scope(Tag = \"mytag\")]\r\npublic void WhenIDoSomethingWithM" +
                    "yTag()\r\n{}\r\n\r\n[When(\"I do something\")]\r\npublic void WhenIDoSomethingNonScoped()\r" +
                    "\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 136
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 137
 testRunner.Then("the binding method \'WhenIDoSomethingWithMyTag\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scoping step definitions of a binding class")]
        public virtual void ScopingStepDefinitionsOfABindingClass()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scoping step definitions of a binding class", ((string[])(null)));
#line 139
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 141
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n\r\n@mytag\r\nScenario: Simple Scenario\r\nWhen I do something" +
                    "", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 149
 testRunner.And("the following binding class", "[Binding, Scope(Tag = \"mytag\")]\r\npublic class ScopedSteps\r\n{\r\n[When(\"I do somethi" +
                    "ng\")]\r\npublic void WhenIDoSomethingWithMyTag()\r\n{}\r\n}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 160
 testRunner.Then("the binding method \'WhenIDoSomethingWithMyTag\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No ambiguouity if the same method matches with multiple scopes")]
        public virtual void NoAmbiguouityIfTheSameMethodMatchesWithMultipleScopes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No ambiguouity if the same method matches with multiple scopes", ((string[])(null)));
#line 163
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 164
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n@mytag\r\nScenario: Simple Scenario\r\nWhen I do something", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 171
 testRunner.And("the following step definition", "[When(\"I do something\"), Scope(Scenario = \"Simple Scenario\"), Scope(Tag = \"mytag\"" +
                    ")]\r\npublic void WhenIDoSomethingInOtherScenarioOrMyTag()\r\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 178
 testRunner.Then("the binding method \'WhenIDoSomethingInOtherScenarioOrMyTag\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("More scope matches have higher precedency")]
        public virtual void MoreScopeMatchesHaveHigherPrecedency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("More scope matches have higher precedency", ((string[])(null)));
#line 180
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 182
 testRunner.Given("there is a feature file in the project as", "Feature: Simple Feature\r\n@mytag\r\nScenario: Simple Scenario\r\nWhen I do something", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 189
 testRunner.And("the following step definition", "[When(\"I do something\"), Scope(Feature = \"Simple Feature\", Tag = \"mytag\")]\r\npubli" +
                    "c void WhenIDoSomethingInSimpleFeatureAndMyTag()\r\n{}\r\n[When(\"I do something\"), S" +
                    "cope(Tag = \"mytag\")]\r\npublic void WhenIDoSomethingWithMyTag()\r\n{}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.When("I execute the tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 199
 testRunner.Then("the binding method \'WhenIDoSomethingInSimpleFeatureAndMyTag\' is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
