// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TechTalk.SpecFlow.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Parser smoke tests")]
    public partial class ParserSmokeTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ParserSmokeTests.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Parser smoke tests", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void TestFilesCanBeParsed(string testFile, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test files can be parsed", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.When(string.Format("the test file \'{0}.feature\' is parsed", testFile), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 5
 testRunner.Then("no parsing error is reported", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: and")]
        public virtual void TestFilesCanBeParsed_And()
        {
            this.TestFilesCanBeParsed("and", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: asterisks")]
        public virtual void TestFilesCanBeParsed_Asterisks()
        {
            this.TestFilesCanBeParsed("asterisks", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: background")]
        public virtual void TestFilesCanBeParsed_Background()
        {
            this.TestFilesCanBeParsed("background", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: background_withtitle")]
        public virtual void TestFilesCanBeParsed_Background_Withtitle()
        {
            this.TestFilesCanBeParsed("background_withtitle", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: but")]
        public virtual void TestFilesCanBeParsed_But()
        {
            this.TestFilesCanBeParsed("but", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: comments")]
        public virtual void TestFilesCanBeParsed_Comments()
        {
            this.TestFilesCanBeParsed("comments", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: dutch")]
        public virtual void TestFilesCanBeParsed_Dutch()
        {
            this.TestFilesCanBeParsed("dutch", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: featureheader")]
        public virtual void TestFilesCanBeParsed_Featureheader()
        {
            this.TestFilesCanBeParsed("featureheader", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: french")]
        public virtual void TestFilesCanBeParsed_French()
        {
            this.TestFilesCanBeParsed("french", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: full")]
        public virtual void TestFilesCanBeParsed_Full()
        {
            this.TestFilesCanBeParsed("full", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: german")]
        public virtual void TestFilesCanBeParsed_German()
        {
            this.TestFilesCanBeParsed("german", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: givenwhenthenduplication")]
        public virtual void TestFilesCanBeParsed_Givenwhenthenduplication()
        {
            this.TestFilesCanBeParsed("givenwhenthenduplication", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: hungarian")]
        public virtual void TestFilesCanBeParsed_Hungarian()
        {
            this.TestFilesCanBeParsed("hungarian", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: mixedgivenwhenthen")]
        public virtual void TestFilesCanBeParsed_Mixedgivenwhenthen()
        {
            this.TestFilesCanBeParsed("mixedgivenwhenthen", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: multilineargument")]
        public virtual void TestFilesCanBeParsed_Multilineargument()
        {
            this.TestFilesCanBeParsed("multilineargument", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: multilinetitle")]
        public virtual void TestFilesCanBeParsed_Multilinetitle()
        {
            this.TestFilesCanBeParsed("multilinetitle", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: scenariooutline")]
        public virtual void TestFilesCanBeParsed_Scenariooutline()
        {
            this.TestFilesCanBeParsed("scenariooutline", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: simple")]
        public virtual void TestFilesCanBeParsed_Simple()
        {
            this.TestFilesCanBeParsed("simple", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: swedish")]
        public virtual void TestFilesCanBeParsed_Swedish()
        {
            this.TestFilesCanBeParsed("swedish", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: tableargument")]
        public virtual void TestFilesCanBeParsed_Tableargument()
        {
            this.TestFilesCanBeParsed("tableargument", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: taggedexamples")]
        public virtual void TestFilesCanBeParsed_Taggedexamples()
        {
            this.TestFilesCanBeParsed("taggedexamples", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: tags")]
        public virtual void TestFilesCanBeParsed_Tags()
        {
            this.TestFilesCanBeParsed("tags", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test files can be parsed: whitespaces")]
        public virtual void TestFilesCanBeParsed_Whitespaces()
        {
            this.TestFilesCanBeParsed("whitespaces", ((string[])(null)));
#line hidden
        }
        
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore(string testFile, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Parsed test files produce the same result as before", exampleTags);
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.When(string.Format("the test file \'{0}.feature\' is parsed", testFile), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then(string.Format("the parsed result is the same as \'{0}.feature.xml\'", testFile), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: and")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_And()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("and", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: asterisks")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Asterisks()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("asterisks", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: background")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Background()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("background", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: background_withtitle")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Background_Withtitle()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("background_withtitle", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: but")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_But()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("but", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: comments")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Comments()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("comments", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: dutch")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Dutch()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("dutch", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: featureheader")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Featureheader()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("featureheader", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: french")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_French()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("french", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: full")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Full()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("full", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: german")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_German()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("german", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: givenwhenthenduplication")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Givenwhenthenduplication()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("givenwhenthenduplication", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: hungarian")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Hungarian()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("hungarian", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: mixedgivenwhenthen")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Mixedgivenwhenthen()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("mixedgivenwhenthen", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: multilineargument")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Multilineargument()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("multilineargument", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: multilinetitle")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Multilinetitle()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("multilinetitle", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: scenariooutline")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Scenariooutline()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("scenariooutline", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: simple")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Simple()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("simple", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: swedish")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Swedish()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("swedish", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: tableargument")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Tableargument()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("tableargument", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: taggedexamples")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Taggedexamples()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("taggedexamples", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: tags")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Tags()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("tags", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsed test files produce the same result as before: whitespaces")]
        public virtual void ParsedTestFilesProduceTheSameResultAsBefore_Whitespaces()
        {
            this.ParsedTestFilesProduceTheSameResultAsBefore("whitespaces", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
