using System;
using System.IO;
using NConsoler;
using TechTalk.SpecFlow.Generator;
using TechTalk.SpecFlow.Generator.Configuration;
using TechTalk.SpecFlow.Reporting.NUnitExecutionReport;
using TechTalk.SpecFlow.Reporting.StepDefinitionReport;
using MsBuildProjectReader = TechTalk.SpecFlow.Generator.Configuration.MsBuildProjectReader;

namespace TechTalk.SpecFlow.Tools
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Consolery.Run(typeof(Program), args);
            return;
        }

        [Action("Generate tests from all feature files in a project")]
        public static void GenerateAll(
            [Required(Description = "Visual Studio Project File containing features")] string projectFile,
            [Optional(false, "force", "f")] bool forceGeneration,
            [Optional(false, "verbose", "v")] bool verboseOutput)
        {
            SpecFlowProject specFlowProject = MsBuildProjectReader.LoadSpecFlowProjectFromMsBuild(projectFile);
            var batchGenerator = new BatchGenerator(Console.Out, verboseOutput);
            batchGenerator.ProcessProject(specFlowProject, forceGeneration);
        }

        #region Reports

        [Action("Generates a report about usage and binding of steps")]
        public static void StepDefinitionReport(
            [Required(Description = "Visual Studio Project File containing specs")] string projectFile,
            [Optional("", Description = "Xslt file to use, defaults to built-in stylesheet if not provided")] string xsltFile,
            [Optional("bin\\Debug", Description = @"Path for Spec dll e.g. Company.Specs.dll. Defaults to bin\Debug ")] string binFolder,
            [Optional("StepDefinitionReport.html", "out", Description = "Generated Output File. Defaults to StepDefinitionReport.html")] string outputFile)
        {
            StepDefinitionReportParameters reportParameters = 
                new StepDefinitionReportParameters(projectFile, outputFile, xsltFile, binFolder, true);
            var generator = new StepDefinitionReportGenerator(reportParameters);
            generator.GenerateAndTransformReport();
        }

        [Action("Formats an NUnit execution report to SpecFlow style")]
        public static void NUnitExecutionReport([Required(Description = "Visual Studio Project File containing specs")] string projectFile,
            [Optional("TestResult.xml", Description = "Xml Test Result file generated by NUnit. Defaults to TestResult.xml")] string xmlTestResult,
            [Optional("", Description = "Xslt file to use, defaults to built-in stylesheet if not provided")] string xsltFile,
            [Optional("TestResult.txt", "testOutput")] string labeledTestOutput,
            [Optional("TestResult.html", "out", Description = "Generated Output File. Defaults to TestResult.html")] string outputFile)
        {
            NUnitExecutionReportParameters reportParameters = 
                new NUnitExecutionReportParameters(projectFile, xmlTestResult, labeledTestOutput, outputFile, xsltFile);         
            var generator = new NUnitExecutionReportGenerator(reportParameters);
            generator.GenerateAndTransformReport();
        }
        
        #endregion
    }
}