// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.1.0.0
//      Runtime Version:2.0.50727.4918
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Bowling.Specflow
{
    using TechTalk.SpecFlow;
    
    
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Score Calculation")]
    public partial class ScoreCalculationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ScoreCalculation.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Score Calculation", "In order to know my performance\r\nAs a player\r\nI want the system to calculate my t" +
                    "otal score", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gutter game")]
        public virtual void GutterGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Gutter game", ((string[])(null)));
#line 6
//#indentnext 0
            this.ScenarioSetup(scenarioInfo);
#line 7
//#indentnext 2
            testRunner.Given("a new bowling game");
#line 8
//#indentnext 2
            testRunner.When("all of my balls are landing in the gutter");
#line 9
//#indentnext 2
            testRunner.Then("my total score should be 0");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Beginners game")]
        public virtual void BeginnersGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Beginners game", ((string[])(null)));
#line 11
//#indentnext 0
            this.ScenarioSetup(scenarioInfo);
#line 12
//#indentnext 2
            testRunner.Given("a new bowling game");
#line 13
//#indentnext 2
            testRunner.When("I roll 2 and 7");
#line 14
//#indentnext 2
            testRunner.And("I roll 3 and 4");
#line 15
//#indentnext 2
            testRunner.And("I roll 8 times 1 and 1");
#line 16
//#indentnext 2
            testRunner.Then("my total score should be 32");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Another beginners game")]
        public virtual void AnotherBeginnersGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Another beginners game", ((string[])(null)));
#line 18
//#indentnext 0
            this.ScenarioSetup(scenarioInfo);
#line 19
//#indentnext 2
            testRunner.Given("a new bowling game");
#line 20
//#indentnext 2
            testRunner.When("I roll the following series:\t2,7,3,4,1,1,5,1,1,1,1,1,1,1,1,1,1,1,5,1");
#line 21
//#indentnext 2
            testRunner.Then("my total score should be 40");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All Strikes")]
        public virtual void AllStrikes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All Strikes", ((string[])(null)));
#line 23
//#indentnext 0
            this.ScenarioSetup(scenarioInfo);
#line 24
//#indentnext 2
            testRunner.Given("a new bowling game");
#line 25
//#indentnext 2
            testRunner.When("all of my rolls are strikes");
#line 26
//#indentnext 2
            testRunner.Then("my total score should be 300");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("One single spare")]
        public virtual void OneSingleSpare()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("One single spare", ((string[])(null)));
#line 28
//#indentnext 0
            this.ScenarioSetup(scenarioInfo);
#line 29
//#indentnext 3
            testRunner.Given("a new bowling game");
#line 30
//#indentnext 3
            testRunner.When("I roll the following series: 2,8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1");
#line 31
//#indentnext 3
            testRunner.Then("my total score should be 29");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All spares")]
        public virtual void AllSpares()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All spares", ((string[])(null)));
#line 33
//#indentnext 0
            this.ScenarioSetup(scenarioInfo);
#line 34
//#indentnext 2
            testRunner.Given("a new bowling game");
#line 35
//#indentnext 2
            testRunner.When("I roll 10 times 1 and 9");
#line 36
//#indentnext 2
            testRunner.And("I roll 1");
#line 37
//#indentnext 2
            testRunner.Then("my total score should be 110");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
